### PR TITLE
pushed initial notification sound functionality

### PR DESCRIPTION
**Pull request by jessefromearth**
A user that goes by the name of 61, suggested that it would be nice if a sound played when a message was received. I implemented this functionality in my notification branch. There wasn't much code to add, but diff is saying that there were 117 additions and what not. I believe this is because my editor decided to change tab spacing.

Let me know what I need to change if I need to, to get it merged!

### CODE REVIEW

**Comment by Antrikshy** [comment]
This seems nice. I will take a look at it when I find time. Why did you close it? More changes coming?

**Comment by jessefromearth** [comment]
Yes I am working on some modifications and I didn't feel it was ready to be merged just yet. I added the ability for users to toggle the volume. I also added a suggestions box, but I put it on the same branch. I should have did a different branch for that, to keep things separate.

**Comment by jessefromearth** [comment]
I've hosted my modifications [here](http://quibbler.breh.xyz/) if you want to see what other additions I've made.

**Comment by jessefromearth** [comment]
How's this looking, @Antrikshy?

**Pull request merged**
